GET http://localhost:3000

###
GET http://localhost:3000/api/v1/pets/adoption?adoption=true

###
GET http://localhost:3000/api/v1/pets/1

###
POST http://localhost:3000/api/v1/pets/
Content-Type: application/json

{
    "id"= 1,
    "name": "Moria",
    "type": "Dog",
    "gender": "Female",
    "description": "is a Dog",
    "approximate_age": 5,
    "image_url": "https://images.dog.ceo/breeds/vizsla/n02100583_12413.jpg",
    "adoption_status": false,
    "approximate_ubication": "Moreno y Las Heras"
}

####
PUT http://localhost:3000/api/v1/pets/62e1a0432add3494543b7566
Content-Type: application/json

{
    "name": "Fluffy",
    "type": "dog",
    "description": "Fluffy is a dog",
    "approximate_age": 4,
    "image_url": "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
    "adoption_status": true,
    "approximate_ubication": "General Paz y Maipu"
}

###
DELETE http://localhost:3000/api/v1/pets/1

PUT http://localhost:3000/api/v1/pets/62e1a0432add3494543b7566
Content-Type: application/json

{
    "adoption_status": true,
    "approximate_ubication": "General Paz y Maipu"
}